fixing release

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -130,7 +130,7 @@ jobs:
           if [ "${{ matrix.goos }}" = "windows" ]; then
             OUTPUT_NAME="${OUTPUT_NAME}.exe"
           fi
-          test -f backend/ui/dist/index.html
+          test -f "${{ github.workspace }}/backend/ui/dist/index.html" || { echo "Frontend UI not found"; exit 1; }
           
           go build -C cmd/pushpaka \
             -ldflags="-w -s -X main.version=v${{ needs.version.outputs.full-version }}" \
